export type CardType = {
  text: string;
  type: "entertainment" | "locations" | "sports" | "outdoors" | "people";
};

export const cards: CardType[] = [
  { text: "Junk Food", type: "entertainment" },
  { text: "Call of Duty", type: "entertainment" },
  { text: "Snapchat", type: "entertainment" },
  { text: "Instagram", type: "entertainment" },
  { text: "Assassin's Creed", type: "entertainment" },
  { text: "Virtual Reality", type: "entertainment" },
  { text: "XBOX", type: "entertainment" },
  { text: "Monopoly", type: "entertainment" },
  { text: "Star Wars", type: "entertainment" },
  { text: "NBC", type: "entertainment" },
  { text: "Computer", type: "entertainment" },
  { text: "Sculpture", type: "entertainment" },
  { text: "Reading", type: "entertainment" },
  { text: "Wi-Fi", type: "entertainment" },
  { text: "Television", type: "entertainment" },
  { text: "Netflix", type: "entertainment" },
  { text: "Dungeons and Dragons", type: "entertainment" },
  { text: "Social Media", type: "entertainment" },
  { text: "Newspaper", type: "entertainment" },
  { text: "Tablet", type: "entertainment" },
  { text: "Magazine", type: "entertainment" },
  { text: "Piano", type: "entertainment" },
  { text: "Novel", type: "entertainment" },
  { text: "Radio", type: "entertainment" },
  { text: "Titanic", type: "entertainment" },
  { text: "12 Angry Men", type: "entertainment" },
  { text: "Gremlins", type: "entertainment" },
  { text: "Shrek", type: "entertainment" },
  { text: "The Godfather", type: "entertainment" },
  { text: "Alien", type: "entertainment" },
  { text: "Annie", type: "entertainment" },
  { text: "Academy Awards", type: "entertainment" },
  { text: "Black Swan", type: "entertainment" },
  { text: "Iron Man", type: "entertainment" },
  { text: "Psycho", type: "entertainment" },
  { text: "The Devil Wears Prada", type: "entertainment" },
  { text: "The Lion King", type: "entertainment" },
  { text: "Aladdin", type: "entertainment" },
  { text: "Ghost", type: "entertainment" },
  { text: "Kung-Fu Panda", type: "entertainment" },
  { text: "The Little Mermaid", type: "entertainment" },
  { text: "Hairspray", type: "entertainment" },
  { text: "Jaws", type: "entertainment" },
  { text: "The Matrix", type: "entertainment" },
  { text: "Black Beauty", type: "entertainment" },
  { text: "X-Men", type: "entertainment" },
  { text: "Twilight", type: "entertainment" },
  { text: "Home Alone", type: "entertainment" },
  { text: "The Simpsons", type: "entertainment" },
  { text: "Game of Thrones", type: "entertainment" },
  { text: "Friends", type: "entertainment" },
  { text: "River Dance", type: "entertainment" },
  { text: "Star Trek", type: "entertainment" },
  { text: "Lazy Boy", type: "entertainment" },
  { text: "Lost", type: "entertainment" },
  { text: "The Da Vinci Code", type: "entertainment" },
  { text: "Little Women", type: "entertainment" },
  { text: "Charlotte's Web", type: "entertainment" },
  { text: "Gone with the Wind", type: "entertainment" },
  { text: "The Grapes of Wrath", type: "entertainment" },
  { text: "The Hunger Games", type: "entertainment" },
  { text: "A Tale of Two Cities", type: "entertainment" },
  { text: "The Cat in the Hat", type: "entertainment" },
  { text: "The Hobbit", type: "entertainment" },
  { text: "My Fair Lady", type: "entertainment" },
  { text: "The Phantom of the Opera", type: "entertainment" },
  { text: "Oklahoma!", type: "entertainment" },
  { text: "Les Miserables", type: "entertainment" },
  { text: "The Book of Mormon", type: "entertainment" },
  { text: "Disco", type: "entertainment" },
  { text: "Beauty and the Beast", type: "entertainment" },
  { text: "Limbo", type: "entertainment" },
  { text: "Macarena", type: "entertainment" },
  { text: "Surprise", type: "entertainment" },
  { text: "Rock Star", type: "entertainment" },
  { text: "Wizard of Oz", type: "entertainment" },
  { text: "Birthday", type: "entertainment" },
  { text: "Excitement", type: "entertainment" },
  { text: "Christmas", type: "entertainment" },
  { text: "Magician", type: "entertainment" },
  { text: "Pizza Party", type: "entertainment" },
  { text: "Funny Bone", type: "entertainment" },
  { text: "Slip 'N Slide", type: "entertainment" },
  { text: "Hello Kitty", type: "entertainment" },
  { text: "Gladiator", type: "entertainment" },
  { text: "Lord of the Rings", type: "entertainment" },
  { text: "Winnie the Pooh", type: "entertainment" },
  { text: "Toy Story", type: "entertainment" },
  { text: "Groundhog Day", type: "entertainment" },
  { text: "U2", type: "entertainment" },
  { text: "Beatles", type: "entertainment" },
  { text: "Rolling Stones", type: "entertainment" },
  { text: "Broadway", type: "entertainment" },
  { text: "Ticket", type: "entertainment" },
  { text: "Coldplay", type: "entertainment" },
  { text: "Popcorn", type: "entertainment" },
  { text: "3D", type: "entertainment" },
  { text: "Comedian", type: "entertainment" },
  { text: "Theater", type: "entertainment" },
  { text: "Tap Dance", type: "entertainment" },
  { text: "Belly Dance", type: "entertainment" },
  { text: "Soprano", type: "entertainment" },
  { text: "Salsa Dance", type: "entertainment" },
  { text: "Bass", type: "entertainment" },
  { text: "Drums", type: "entertainment" },
  { text: "Model", type: "entertainment" },
  { text: "Cello", type: "entertainment" },
  { text: "Runway", type: "entertainment" },
  { text: "Tuxedo", type: "entertainment" },
  { text: "Red Carpet", type: "entertainment" },
  { text: "High Heels", type: "entertainment" },
  { text: "Moon Walk", type: "entertainment" },
  { text: "Email", type: "entertainment" },
  { text: "Text Message", type: "entertainment" },
  { text: "Selfie", type: "entertainment" },
  { text: "DVD Player", type: "entertainment" },
  { text: "Duck Hunt", type: "entertainment" },
  { text: "Mario Kart", type: "entertainment" },
  { text: "Bow Tie", type: "entertainment" },
  { text: "Uno", type: "entertainment" },
  { text: "George Washington", type: "people" },
  { text: "Henry Ford", type: "people" },
  { text: "Indian", type: "people" },
  { text: "Barack Obama", type: "people" },
  { text: "Dizzy", type: "people" },
  { text: "Secretary", type: "people" },
  { text: "Caesar Augustus", type: "people" },
  { text: "Vomit", type: "people" },
  { text: "Manager", type: "people" },
  { text: "Cousin", type: "people" },
  { text: "Thinking", type: "people" },
  { text: "Editor", type: "people" },
  { text: "Tickle", type: "people" },
  { text: "Queen", type: "people" },
  { text: "Water Bottle", type: "people" },
  { text: "Tweezers", type: "people" },
  { text: "Wedding", type: "people" },
  { text: "Boots", type: "people" },
  { text: "Proposal", type: "people" },
  { text: "Garbage", type: "people" },
  { text: "Creepy", type: "people" },
  { text: "Birth", type: "people" },
  { text: "Menu", type: "people" },
  { text: "Rent", type: "people" },
  { text: "Bus Driver", type: "people" },
  { text: "Voice", type: "people" },
  { text: "War", type: "people" },
  { text: "Couple", type: "people" },
  { text: "Police Officer", type: "people" },
  { text: "Club", type: "people" },
  { text: "Author", type: "people" },
  { text: "Diaper", type: "people" },
  { text: "Britney Spears", type: "people" },
  { text: "Sign Language", type: "people" },
  { text: "Traffic", type: "people" },
  { text: "Teacher", type: "people" },
  { text: "Audience", type: "people" },
  { text: "Kiss", type: "people" },
  { text: "Credit Card", type: "people" },
  { text: "Community", type: "people" },
  { text: "Love", type: "people" },
  { text: "Gold Digger", type: "people" },
  { text: "Wink and Smile", type: "people" },
  { text: "Cigar", type: "people" },
  { text: "Beyoncé", type: "people" },
  { text: "Wallet", type: "people" },
  { text: "Cowboy", type: "people" },
  { text: "Shakira", type: "people" },
  { text: "Pregnant", type: "people" },
  { text: "Doctor", type: "people" },
  { text: "Politician", type: "people" },
  { text: "Event Planner", type: "people" },
  { text: "Population", type: "people" },
  { text: "President", type: "people" },
  { text: "Student", type: "people" },
  { text: "Relationship", type: "people" },
  { text: "Customer", type: "people" },
  { text: "Dealer", type: "people" },
  { text: "Driver's License", type: "people" },
  { text: "Death", type: "people" },
  { text: "Blood", type: "people" },
  { text: "Expression", type: "people" },
  { text: "Mood", type: "people" },
  { text: "Payment", type: "people" },
  { text: "Heartbeat", type: "people" },
  { text: "Justin Bieber", type: "people" },
  { text: "Money", type: "people" },
  { text: "Superman", type: "people" },
  { text: "Spiderman", type: "people" },
  { text: "Frankenstein", type: "people" },
  { text: "Zombie", type: "people" },
  { text: "Cat Woman", type: "people" },
  { text: "Neighbor", type: "people" },
  { text: "Father", type: "people" },
  { text: "Charles Darwin", type: "people" },
  { text: "Harry Potter", type: "people" },
  { text: "Dinner", type: "people" },
  { text: "Abraham Lincoln", type: "people" },
  { text: "Frown", type: "people" },
  { text: "Donald Trump", type: "people" },
  { text: "Clown", type: "people" },
  { text: "Christopher Columbus", type: "people" },
  { text: "Braces", type: "people" },
  { text: "Albert Einstein", type: "people" },
  { text: "Pollution", type: "people" },
  { text: "Dog Trainer", type: "people" },
  { text: "Pirate", type: "people" },
  { text: "Rolex Watch", type: "people" },
  { text: "Test", type: "people" },
  { text: "Taxes", type: "people" },
  { text: "Fat", type: "people" },
  { text: "Pablo Picasso", type: "people" },
  { text: "Walt Disney", type: "people" },
  { text: "Leonardo Da Vinci", type: "people" },
  { text: "Beethoven", type: "people" },
  { text: "Thomas Edison", type: "people" },
  { text: "Michael Jackson", type: "people" },
  { text: "Alexander Hamilton", type: "people" },
  { text: "Mohawk", type: "people" },
  { text: "Standing Ovation", type: "people" },
  { text: "Haircut", type: "people" },
  { text: "Halo", type: "people" },
  { text: "Steve Jobs", type: "people" },
  { text: "Hiccup", type: "people" },
  { text: "Singer", type: "people" },
  { text: "Cradle", type: "people" },
  { text: "Hungry", type: "people" },
  { text: "Drool", type: "people" },
  { text: "Handshake", type: "people" },
  { text: "Makeup", type: "people" },
  { text: "Firefighter", type: "people" },
  { text: "Mirror", type: "people" },
  { text: "Spaghetti", type: "people" },
  { text: "Nosey", type: "people" },
  { text: "Nightmare", type: "people" },
  { text: "Mickey Mouse", type: "people" },
  { text: "Elvis Presley", type: "people" },
  { text: "Head Over Heals", type: "people" },
  { text: "Chickenpox", type: "people" },
  { text: "Girlfriend", type: "people" },
  { text: "Antlers", type: "outdoors" },
  { text: "Fireflies", type: "outdoors" },
  { text: "Hoof", type: "outdoors" },
  { text: "Sour", type: "outdoors" },
  { text: "Worm", type: "outdoors" },
  { text: "Scavenger Hunt", type: "outdoors" },
  { text: "Chalk", type: "outdoors" },
  { text: "Sunrise", type: "outdoors" },
  { text: "Sand", type: "outdoors" },
  { text: "Naked", type: "outdoors" },
  { text: "Wave", type: "outdoors" },
  { text: "Dig", type: "outdoors" },
  { text: "Roots", type: "outdoors" },
  { text: "I Spy", type: "outdoors" },
  { text: "Lava", type: "outdoors" },
  { text: "Peanuts", type: "outdoors" },
  { text: "Water", type: "outdoors" },
  { text: "Potato", type: "outdoors" },
  { text: "Orange", type: "outdoors" },
  { text: "Blue Bird", type: "outdoors" },
  { text: "Diamond", type: "outdoors" },
  { text: "Nature", type: "outdoors" },
  { text: "Apple", type: "outdoors" },
  { text: "Horns", type: "outdoors" },
  { text: "Meat", type: "outdoors" },
  { text: "Insect", type: "outdoors" },
  { text: "Weeds", type: "outdoors" },
  { text: "Mud", type: "outdoors" },
  { text: "Salmon", type: "outdoors" },
  { text: "Forest Fire", type: "outdoors" },
  { text: "Air", type: "outdoors" },
  { text: "Sun Screen", type: "outdoors" },
  { text: "Lawn Mower", type: "outdoors" },
  { text: "Mouse", type: "outdoors" },
  { text: "Soil", type: "outdoors" },
  { text: "Space", type: "outdoors" },
  { text: "Chicken", type: "outdoors" },
  { text: "Salt", type: "outdoors" },
  { text: "Weather", type: "outdoors" },
  { text: "Wind", type: "outdoors" },
  { text: "Exit", type: "outdoors" },
  { text: "Plant", type: "outdoors" },
  { text: "Constellation", type: "outdoors" },
  { text: "Summer", type: "outdoors" },
  { text: "Monsoon", type: "outdoors" },
  { text: "Sky", type: "outdoors" },
  { text: "Wing", type: "outdoors" },
  { text: "Fruit", type: "outdoors" },
  { text: "Log", type: "outdoors" },
  { text: "Season", type: "outdoors" },
  { text: "Vegetable", type: "outdoors" },
  { text: "Dinosaur", type: "outdoors" },
  { text: "Sunburn", type: "outdoors" },
  { text: "Wheelbarrow", type: "outdoors" },
  { text: "Ladder", type: "outdoors" },
  { text: "Deer", type: "outdoors" },
  { text: "Giraffe", type: "outdoors" },
  { text: "Hedgehog", type: "outdoors" },
  { text: "Flashlight", type: "outdoors" },
  { text: "Hurricane", type: "outdoors" },
  { text: "Rainbow", type: "outdoors" },
  { text: "Spider", type: "outdoors" },
  { text: "Monster", type: "outdoors" },
  { text: "Mosquito Bite", type: "outdoors" },
  { text: "Bulldog", type: "outdoors" },
  { text: "Shovel", type: "outdoors" },
  { text: "Thunder", type: "outdoors" },
  { text: "Boar", type: "outdoors" },
  { text: "Cherry Tree", type: "outdoors" },
  { text: "Parrot", type: "outdoors" },
  { text: "Wheat", type: "outdoors" },
  { text: "Leopard", type: "outdoors" },
  { text: "Bumble Bee", type: "outdoors" },
  { text: "Tiger", type: "outdoors" },
  { text: "Grizzly Bear", type: "outdoors" },
  { text: "Opossum", type: "outdoors" },
  { text: "Walrus", type: "outdoors" },
  { text: "Puppy", type: "outdoors" },
  { text: "Donkey", type: "outdoors" },
  { text: "Mountain Goat", type: "outdoors" },
  { text: "Kangaroo", type: "outdoors" },
  { text: "Ferret", type: "outdoors" },
  { text: "Panther", type: "outdoors" },
  { text: "Iguana", type: "outdoors" },
  { text: "Turtle", type: "outdoors" },
  { text: "Bison", type: "outdoors" },
  { text: "Rooster", type: "outdoors" },
  { text: "Butterfly", type: "outdoors" },
  { text: "Flea", type: "outdoors" },
  { text: "Daisy", type: "outdoors" },
  { text: "Dragonfly", type: "outdoors" },
  { text: "Honeysuckle", type: "outdoors" },
  { text: "Banana", type: "outdoors" },
  { text: "Pear", type: "outdoors" },
  { text: "Coconut", type: "outdoors" },
  { text: "Lemon", type: "outdoors" },
  { text: "Spinach", type: "outdoors" },
  { text: "Squash", type: "outdoors" },
  { text: "Onion", type: "outdoors" },
  { text: "Owl", type: "outdoors" },
  { text: "Goose", type: "outdoors" },
  { text: "Gloves", type: "outdoors" },
  { text: "Oats", type: "outdoors" },
  { text: "Chainsaw", type: "outdoors" },
  { text: "Seeds", type: "outdoors" },
  { text: "Allergies", type: "outdoors" },
  { text: "Pinecones", type: "outdoors" },
  { text: "Claws", type: "outdoors" },
  { text: "Pumpkin", type: "outdoors" },
  { text: "Snowman", type: "outdoors" },
  { text: "Tomatoes", type: "outdoors" },
  { text: "Snowflake", type: "outdoors" },
  { text: "Safari", type: "outdoors" },
  { text: "Manure", type: "outdoors" },
  { text: "Leaf", type: "outdoors" },
  { text: "Pitchfork", type: "outdoors" },
  { text: "Grazing", type: "outdoors" },
  { text: "Migration", type: "outdoors" },
  { text: "Hay", type: "outdoors" },
  { text: "Blowhole", type: "outdoors" },
  { text: "Shower", type: "locations" },
  { text: "Farm", type: "locations" },
  { text: "Stoplight", type: "locations" },
  { text: "Mecca", type: "locations" },
  { text: "Gym", type: "locations" },
  { text: "Fence", type: "locations" },
  { text: "Brick Oven", type: "locations" },
  { text: "Garden", type: "locations" },
  { text: "McDonalds", type: "locations" },
  { text: "End Zone", type: "locations" },
  { text: "Park", type: "locations" },
  { text: "Temple", type: "locations" },
  { text: "Sphinx", type: "locations" },
  { text: "Tower of Pisa", type: "locations" },
  { text: "Castle", type: "locations" },
  { text: "Chimney", type: "locations" },
  { text: "Library", type: "locations" },
  { text: "Oven", type: "locations" },
  { text: "Mosque", type: "locations" },
  { text: "Chatroom", type: "locations" },
  { text: "University", type: "locations" },
  { text: "Clouds", type: "locations" },
  { text: "Country", type: "locations" },
  { text: "Road", type: "locations" },
  { text: "Mall", type: "locations" },
  { text: "Stairs", type: "locations" },
  { text: "Apartment", type: "locations" },
  { text: "Forest", type: "locations" },
  { text: "Jail", type: "locations" },
  { text: "Office", type: "locations" },
  { text: "Lake", type: "locations" },
  { text: "Duplex", type: "locations" },
  { text: "Dormitory", type: "locations" },
  { text: "Classroom", type: "locations" },
  { text: "City", type: "locations" },
  { text: "Hotel", type: "locations" },
  { text: "Elevator", type: "locations" },
  { text: "Refrigerator", type: "locations" },
  { text: "Bath", type: "locations" },
  { text: "Church", type: "locations" },
  { text: "Airport", type: "locations" },
  { text: "Hospital", type: "locations" },
  { text: "Restaurant", type: "locations" },
  { text: "River", type: "locations" },
  { text: "Super Market", type: "locations" },
  { text: "Urinal", type: "locations" },
  { text: "Barbershop", type: "locations" },
  { text: "Bedroom", type: "locations" },
  { text: "Private School", type: "locations" },
  { text: "Roof", type: "locations" },
  { text: "Funeral", type: "locations" },
  { text: "Waterfall", type: "locations" },
  { text: "Bridge", type: "locations" },
  { text: "Kitchen", type: "locations" },
  { text: "Great Wall of China", type: "locations" },
  { text: "Hong Kong", type: "locations" },
  { text: "Brazil", type: "locations" },
  { text: "Amazon", type: "locations" },
  { text: "Treasure Map", type: "locations" },
  { text: "Nile River", type: "locations" },
  { text: "Pyramids", type: "locations" },
  { text: "California", type: "locations" },
  { text: "Athens", type: "locations" },
  { text: "Island", type: "locations" },
  { text: "Lagoon", type: "locations" },
  { text: "Volcano", type: "locations" },
  { text: "Indian Sea", type: "locations" },
  { text: "Cliff", type: "locations" },
  { text: "Beach", type: "locations" },
  { text: "Valley", type: "locations" },
  { text: "Canyon", type: "locations" },
  { text: "Stone-Henge", type: "locations" },
  { text: "Eiffel Tower", type: "locations" },
  { text: "Colosseum", type: "locations" },
  { text: "Statue", type: "locations" },
  { text: "Grand Canyon", type: "locations" },
  { text: "Empire State Building", type: "locations" },
  { text: "Las Vegas", type: "locations" },
  { text: "Hawaii", type: "locations" },
  { text: "Niagra Falls", type: "locations" },
  { text: "Casino", type: "locations" },
  { text: "Pier", type: "locations" },
  { text: "Windy City", type: "locations" },
  { text: "Rocky Mountains", type: "locations" },
  { text: "Mount Everest", type: "locations" },
  { text: "Capital", type: "locations" },
  { text: "Tokyo", type: "locations" },
  { text: "Statue of Liberty", type: "locations" },
  { text: "Vatican", type: "locations" },
  { text: "Museum", type: "locations" },
  { text: "Taj Mahal", type: "locations" },
  { text: "Haunted House", type: "locations" },
  { text: "Jungle", type: "locations" },
  { text: "Pasture", type: "locations" },
  { text: "Porch", type: "locations" },
  { text: "Out-House", type: "locations" },
  { text: "Picnic", type: "locations" },
  { text: "Zoo", type: "locations" },
  { text: "Jupiter", type: "locations" },
  { text: "Compass", type: "locations" },
  { text: "Mars", type: "locations" },
  { text: "Courthouse", type: "locations" },
  { text: "Swimming Pool", type: "locations" },
  { text: "Pew", type: "locations" },
  { text: "Garage", type: "locations" },
  { text: "Swing", type: "locations" },
  { text: "Skyscraper", type: "locations" },
  { text: "Shed", type: "locations" },
  { text: "Dinner Table", type: "locations" },
  { text: "White House", type: "locations" },
  { text: "Pentagon", type: "locations" },
  { text: "Tour", type: "locations" },
  { text: "Escalator", type: "locations" },
  { text: "Paint Bucket", type: "locations" },
  { text: "Two By Four", type: "locations" },
  { text: "Flush", type: "locations" },
  { text: "Alleyway", type: "locations" },
  { text: "Roller Coaster", type: "locations" },
  { text: "Disneyland", type: "locations" },
  { text: "Crosswalk", type: "locations" },
  { text: "Net", type: "sports" },
  { text: "Goggles", type: "sports" },
  { text: "Tiger Woods", type: "sports" },
  { text: "Flippers", type: "sports" },
  { text: "Marathon", type: "sports" },
  { text: "Rodeo", type: "sports" },
  { text: "Water Polo", type: "sports" },
  { text: "Mouth Guard", type: "sports" },
  { text: "Out of Bounds", type: "sports" },
  { text: "Helmet", type: "sports" },
  { text: "Push Up", type: "sports" },
  { text: "Shotput", type: "sports" },
  { text: "Technical Foul", type: "sports" },
  { text: "Yellow Card", type: "sports" },
  { text: "Turf", type: "sports" },
  { text: "Cross Fit", type: "sports" },
  { text: "Protein Shake", type: "sports" },
  { text: "Headphones", type: "sports" },
  { text: "Massage", type: "sports" },
  { text: "Gold Medal", type: "sports" },
  { text: "Pilates", type: "sports" },
  { text: "Camera", type: "sports" },
  { text: "Pull-Up Bar", type: "sports" },
  { text: "Cross Country", type: "sports" },
  { text: "Driver", type: "sports" },
  { text: "Health", type: "sports" },
  { text: "Convertible", type: "sports" },
  { text: "Temperature", type: "sports" },
  { text: "Punch", type: "sports" },
  { text: "Equipment", type: "sports" },
  { text: "Dumbbells", type: "sports" },
  { text: "ESPN", type: "sports" },
  { text: "Round", type: "sports" },
  { text: "Photograph", type: "sports" },
  { text: "Bear Trap", type: "sports" },
  { text: "Barbeque", type: "sports" },
  { text: "Guitar", type: "sports" },
  { text: "Tennis", type: "sports" },
  { text: "Football", type: "sports" },
  { text: "Buzzer", type: "sports" },
  { text: "Winner", type: "sports" },
  { text: "Championship", type: "sports" },
  { text: "Baseball", type: "sports" },
  { text: "Game", type: "sports" },
  { text: "Exercise", type: "sports" },
  { text: "Boat", type: "sports" },
  { text: "Sport", type: "sports" },
  { text: "Record", type: "sports" },
  { text: "Shotgun", type: "sports" },
  { text: "Brush", type: "sports" },
  { text: "Head To Head", type: "sports" },
  { text: "Track", type: "sports" },
  { text: "Muscle", type: "sports" },
  { text: "Balance Beam", type: "sports" },
  { text: "Bulls Eye", type: "sports" },
  { text: "Ballet", type: "sports" },
  { text: "Fly Fishing", type: "sports" },
  { text: "Gallop", type: "sports" },
  { text: "Balloon", type: "sports" },
  { text: "Hurt", type: "sports" },
  { text: "Karate", type: "sports" },
  { text: "Waltz", type: "sports" },
  { text: "Ice Skating", type: "sports" },
  { text: "Slippery", type: "sports" },
  { text: "Stubbed Toe", type: "sports" },
  { text: "Jump Rope", type: "sports" },
  { text: "Soccer", type: "sports" },
  { text: "Sword", type: "sports" },
  { text: "Kite", type: "sports" },
  { text: "Motorcycle", type: "sports" },
  { text: "Helicopter", type: "sports" },
  { text: "Roller Coaster", type: "sports" },
  { text: "Yo-Yo", type: "sports" },
  { text: "Kung Fu", type: "sports" },
  { text: "Trampoline", type: "sports" },
  { text: "Badminton", type: "sports" },
  { text: "Curling", type: "sports" },
  { text: "Bat", type: "sports" },
  { text: "Skiing", type: "sports" },
  { text: "Surfing", type: "sports" },
  { text: "Gym Rat", type: "sports" },
  { text: "Poker", type: "sports" },
  { text: "Horse Race", type: "sports" },
  { text: "Boxing", type: "sports" },
  { text: "Puck", type: "sports" },
  { text: "Figure Skating", type: "sports" },
  { text: "Putter", type: "sports" },
  { text: "Michael Jordan", type: "sports" },
  { text: "Goalie", type: "sports" },
  { text: "Quarterback", type: "sports" },
  { text: "Strike", type: "sports" },
  { text: "NASCAR", type: "sports" },
  { text: "Video Game", type: "sports" },
  { text: "Muhammad Ali", type: "sports" },
  { text: "Rollerblade", type: "sports" },
  { text: "Camping", type: "sports" },
  { text: "Hiking", type: "sports" },
  { text: "Tent", type: "sports" },
  { text: "Rock Climb", type: "sports" },
  { text: "Cycling", type: "sports" },
  { text: "Running", type: "sports" },
  { text: "Snorkel", type: "sports" },
  { text: "Hunt", type: "sports" },
  { text: "Sweat", type: "sports" },
  { text: "Stadium", type: "sports" },
  { text: "Olympics", type: "sports" },
  { text: "Cleats", type: "sports" },
  { text: "Javelin", type: "sports" },
  { text: "Skydiving", type: "sports" },
  { text: "Treadmill", type: "sports" },
  { text: "Sail Boat", type: "sports" },
  { text: "Hurdles", type: "sports" },
  { text: "Dominos", type: "sports" },
  { text: "Penalty Kick", type: "sports" },
  { text: "Backflip", type: "sports" },
  { text: "Free Throw", type: "sports" },
  { text: "Golf Tee", type: "sports" },
  { text: "Yoga", type: "sports" },
  { text: "Slice", type: "sports" },
  { text: "Bull Riding", type: "sports" },
];
